---

- name: disable wpa supplicant
  systemd:
    name: wpa_supplicant
    state: stopped
    enabled: no

- name: disable dhcp client
  systemd:
    name: dhcpcd
    state: stopped
    enabled: no

- name: install networking deps
  apt:
    pkg:
      - isc-dhcp-server
    state: present

- name: add DHCP daemon configs
  template:
    src: dhcpd.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: install custom interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces.d/eth0
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify: restart networking